required = ["k8s.io/code-generator/cmd/client-gen"]

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.13"

[[override]]
  name = "k8s.io/apiserver"
  branch = "release-1.13"

[[override]]
  name = "k8s.io/client-go"
  version = "v10.0.0"

[[override]]
  name = "k8s.io/code-generator"
  branch = "release-1.13"

[[constraint]]
  name = "github.com/gobuffalo/plush"
  version = "3.7.32"
