required = ["k8s.io/code-generator/cmd/client-gen"]

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.11"

[[override]]
  name = "k8s.io/apiserver"
  branch = "release-1.11"

[[override]]
  name = "k8s.io/client-go"
  version = "v8.0.0"

[[override]]
  name = "k8s.io/code-generator"
  branch = "release-1.11"

# vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go:104:16:
# unknown field 'CaseSensitive' in struct literal of type jsoniter.Config
[[override]]
  name = "github.com/json-iterator/go"
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

[[constraint]]
  name = "github.com/gobuffalo/plush"
  version = "3.7.1"
