---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: lessor-controller
  name: lessor-controller
  namespace: lessor-system
spec:
  selector:
    matchLabels:
      name: lessor-controller
  template:
    metadata:
      labels:
        name: lessor-controller
      name: lessor-controller
    spec:
      containers:
      - name: lessor-controller
        command:
        - lessor
        - run
        - controller
        - --debug
        image: gcr.io/lessor-io/lessor:latest
        imagePullPolicy: Always
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tenants.lessor.io
spec:
  group: lessor.io
  names:
    kind: Tenant
    listKind: TenantList
    plural: tenants
    singular: tenant
  scope: Namespaced
  version: v1
---
apiVersion: v1
kind: Namespace
metadata:
  name: lessor-system
