// Code generated by lister-gen. DO NOT EDIT.

package v1

// TenantListerExpansion allows custom methods to be added to
// TenantLister.
type TenantListerExpansion interface{}

// TenantNamespaceListerExpansion allows custom methods to be added to
// TenantNamespaceLister.
type TenantNamespaceListerExpansion interface{}
