version: 2
jobs:
  build:
    docker:
      - image: golang:1.11.2
    working_directory: /go/src/github.com/lessor/lessor
    steps: &steps
      - checkout
      - run: make deps
      - run: make test
      - run: make lint
      - run: make build
workflows:
  version: 2
  build:
    jobs:
      - build
