version: 2
jobs:
  build-go1.10.1:
    docker:
        - image: golang:1.10.1
    working_directory: /go/src/github.com/lessor/lessor
    steps: &steps
      - checkout
      - run: go get -u github.com/alecthomas/gometalinter
      - run: gometalinter --install
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: dep ensure -vendor-only
      - run: >
          gometalinter --disable-all \
            --enable=vet \
            --enable=vetshadow \
            --enable=golint \
            --enable=misspell \
            --skip=client \
            --skip=apis \
            ./pkg/...
      - run: go test -race -cover -v ./...
      - run: go build
workflows:
  version: 2
  build:
    jobs:
      - build-go1.10.1
