apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: kuard
  name: kuard
  namespace: {{ index . "namespace" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kuard
  template:
    metadata:
      labels:
        run: kuard
    spec:
      containers:
      - image: {{ index . "image" }}
        imagePullPolicy: IfNotPresent
        name: kuard
