// This file was automatically generated by informer-gen

package v1

import (
	internalinterfaces "github.com/lessor/lessor/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Tenants returns a TenantInformer.
	Tenants() TenantInformer
}

type version struct {
	internalinterfaces.SharedInformerFactory
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory) Interface {
	return &version{f}
}

// Tenants returns a TenantInformer.
func (v *version) Tenants() TenantInformer {
	return &tenantInformer{factory: v.SharedInformerFactory}
}
