---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: lessor-controller
  name: lessor-controller
  namespace: lessor-system
spec:
  selector:
    matchLabels:
      name: lessor-controller
  template:
    metadata:
      labels:
        name: lessor-controller
      name: lessor-controller
    spec:
      containers:
      - name: lessor-controller
        command:
        - lessor
        - run
        - controller
        - --debug
        image: gcr.io/lessor-io/lessor:latest
        imagePullPolicy: Always
